### ISSUE TITLE
Shell switches

### ISSUE THREAD

**Issue by p00f** [p00f/adwaita-dracula#1]
![image](https://user-images.githubusercontent.com/36493671/95675474-33cdd880-0bd5-11eb-86c3-f2a91664d06f.png)
@lonr @daniruiz any idea?

**Comment by daniruiz** [comment]
![image](https://user-images.githubusercontent.com/12565871/95675555-65847680-0bb8-11eb-8209-05250d97014b.png)

Are you using POP OS?

**Comment by p00f** [comment]
Nope I'm using archlinux

11-Oct-2020 3:23:59 PM DяA <notifications@github.com>:

**Comment by daniruiz** [comment]
Hum, so do I. That's weird.  
Do you have the latest version installed?

**Comment by daniruiz** [comment]
Lol I thought this issue was on flat-remix-gnome. Your theme is missing all the assets for gnome-shell, so it's pulling the ones from gnome

**Comment by p00f** [comment]
haha

**Comment by p00f** [comment]
@lonr
> TODO: replace assets references in GTK theme

Is this the same issue?

**Comment by p00f** [comment]
@daniruiz Does it mean i need to create my own switches?

**Comment by p00f** [comment]
If that is the case i plan to hand-edit the svg using a text editor

**Comment by lonr** [comment]
> @lonr
> 
> > TODO: replace assets references in GTK theme
> 
> Is this the same issue? (because the TODO says gtk but I think this is a shell element)

No, as you thought: you(and I) need to edit those svgs. 

And "TODO" should be "NOT TODO": what I wanted TODO is just let the generated theme use builtin Adwaita assets. (doesn't solve this issue)

**Comment by p00f** [comment]
:+1:

**Comment by p00f** [comment]
> And as daniruiz mentioned, assets references(like url("resource:///org/gnome/shell/theme/dash-placeholder.svg") ) in GNOME Shell scss files should also be changed.

How do I do that though? I changed `src/gnome-shell/gnome-shell-sass/widgets/_switches.scss` to
```css
/* Switches */

// these are equal to the size of the SVG assets
$switch_height: 22px;
$switch_width: 46px;

.toggle-switch {
  color: $fg_color;
  height: $switch_height;
  width: $switch_width;
  background-size: contain;
  background-image: if($variant == 'light', url("resource:///org/gnome/shell/theme/toggle-off.svg"),url('../../toggle-off-dark.svg'));
  &:checked { 
    background-image: if($variant == 'light', url("resource:///org/gnome/shell/theme/toggle-on.svg"),url('../../toggle-on-dark.svg'));
  }
}
```
and modified the svgs(https://github.com/p00f/adwaita-dracula/blob/master/src/gnome-shell/toggle-on-dark.svg) but I get this https://imgur.com/rn9I4kJ

(invisible, likely that it didn't find the svg)
